include $(TOPDIR)/rules.mk

LUCI_TITLE:=ThroughWall WiFi Boost (NR3053)
LUCI_DEPENDS:=+luci-base

PKG_LICENSE:=MIT
PKG_MAINTAINER:=Viettel Fork

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
