# MT7981 DBDC band steering (ra0=2.4G, rax0=5G)
BndStrgEnable=1
BndStrgRssiPref=0
RssiThreshold=-70
RssiLow=-80
RssiDiff=15
AgeTime=30000
HoldTime=30000
CheckTime_5G=30000
CheckTime_2G=30000
FrameCheck=0x01
ConditionCheck=0x01
